base:
    serial_number: ""
    service_name: ""
    service_displayname: ""
    sercice_desc: ""
    is_dev: false
ssh:
    ip: 127.0.0.1
    port: 22
    username: ubuntu
    password: 123456
cmd:
  - cd /var/log/
  - ls